### ISSUE TITLE
Feat_Appointments

### ISSUE THREAD

**Issue by gofat70** [williamchh/Tafe19S105#4]
Hi team
I'm having problem with the delete function at the moment.
Could you all have a look, and see where i went wrong.
Regards Erik

**Comment by tafesadtl** [comment]
Try adding a line of code to check if the data has been updated or not

**Comment by williamchh** [comment]
try to use Appointments class Primary Key ID instead of string EventName

**Comment by gofat70** [comment]
Thanks for all your help
